- The site is made available by Herd, and will be available at: https?://[kebab-case-project-dir].test. Use the `get-absolute-url` tool to generate URLs for the user to ensure user satisfaction and valid URLs.
- You must not run any commands to make the site available via HTTP(s). It is _always_ available through Herd.
